### PR TITLE
Add 2 new strings

### PR DESCRIPTION
**Pull request by schinken**
New translations as requested in pull #1

### CODE REVIEW

**Comment by meher421** [comment]
Short description

**Comment by schinken** [comment]
hm? the short description is now 75 chars long

**Comment by meher421** [comment]
Hi , Can you please provide the below Strings in German language,New feature added and will be released soon.

<string name="title_premium">Go Premium</string>
 <string name="summary_go_premium">Removes advertisements</string>

**Comment by schinken** [comment]
Nutze Premium
Werbefrei

**Comment by meher421** [comment]
Hi,

There are few strings added in the Apk Extractor application.Request you to
translate the strings in your respective language and send me in
email/Github.Please maintain the same order or map the strings
respectively.

Strings are placed in the below link:

https://github.com/meher421/ExtractorStrings/issues

Regards
Meher Prasad

**Pull request closed without merging**
