### PR TITLE
Add German translation

### PR DESCRIPTION
**Pull request by schinken**
Provides german translations

### CODE REVIEW

**Comment by meher421** [comment]
Hi schinken,
I have added a new feature in Apk Extractor,can you please provide translations for the below strings 

<string-array name="listarray">
        <item>Name + Version + Version Code</item>
        <item> Name + Version</item>
        <item> Name</item>
</string-array>

     <string name="file_name_format">Apk file name saving format</string>
    <string name="name_format_type_summary">Extracted application naming convention</string>

**Comment by schinken** [comment]
Hi meher421,

yes I can provide another pull-request with the translations. But what do you mean with "Apk file name saving format" and "Extracted application naming convention" 

I need a little bit more context. You can use the strings "Name", "Version" and "Versionsnummer" (Version Code) as the translation.

**Comment by meher421** [comment]
I am adding a new feature which will help user to choose the Apk file format name when it is saved on to SD card.
current convention is say ApkExtractor_3.03_27.apk. (AppName + Version Name + Version Code)

and there is no way user can modify it.

Now user choose three different options:
1. ApkExtractor
2.ApkExtracotr_3.03
3.ApkExtractor_3.03_27.apk

Here "Extracted application naming convention" is the title for the above setting in Settings screen.

**Comment by meher421** [comment]
Hi Schinken,
 Can you please re-write the app short description,as play store has text field which is limited to 80 chars, and current string does not fit in it.

**Comment by schinken** [comment]
done

**Pull request merged**
